name: CD

on:
  push:
    branches: [master]

jobs:
  push-to-vm:
    name: Push to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Virtual Environment
        run: pip install -r requirements.txt

      - name: Build site
        run: make build

      - name: Push to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "output/"
          target: "kalemiller.com/blog/"
